//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyNewStreetLight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplyNewStreetLight()
        {
            this.ApplyNewStreetLightImgs = new HashSet<ApplyNewStreetLightImg>();
        }
    
        public int ApplyNewStreetLightID { get; set; }
        public string ReferenceNumber { get; set; }
        public string TrafficLightName { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Logititude { get; set; }
        public Nullable<System.DateTime> DateOfComplaint { get; set; }
        public Nullable<System.TimeSpan> TimeOfComplaint { get; set; }
        public Nullable<System.DateTime> DateOfAction { get; set; }
        public Nullable<System.TimeSpan> TimeOfAction { get; set; }
        public string CauseOfProblem { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplyNewStreetLightImg> ApplyNewStreetLightImgs { get; set; }
    }
}
