//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassificationCameraList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassificationCameraList()
        {
            this.ClassificationAlarms = new HashSet<ClassificationAlarm>();
            this.ClassificationDatas = new HashSet<ClassificationData>();
        }
    
        public int Id { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public Nullable<int> CompanyProfileId { get; set; }
        public Nullable<int> JunctionId { get; set; }
        public string PhaseName { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string JunctionName { get; set; }
        public string NameOfPhase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassificationAlarm> ClassificationAlarms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassificationData> ClassificationDatas { get; set; }
    }
}
