//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassificationData
    {
        public int Id { get; set; }
        public string CameraId { get; set; }
        public Nullable<int> CameraListId { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public string Status { get; set; }
        public string TotalLane { get; set; }
        public string CountTime { get; set; }
        public string LaneNumber { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.DateTime> Hour { get; set; }
        public string HeadWay { get; set; }
        public string HighSpeedVehicle { get; set; }
        public string LowSpeedVehicle { get; set; }
        public string ClassA { get; set; }
        public string ClassB { get; set; }
        public string ClassC { get; set; }
        public string ClassD { get; set; }
        public string ClasseE { get; set; }
        public string TotalLaneStatus { get; set; }
        public string CheckSum { get; set; }
    
        public virtual ClassificationCameraList ClassificationCameraList { get; set; }
    }
}
