//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenTimeArchive
    {
        public int Id { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public Nullable<int> F1_Sec { get; set; }
        public Nullable<int> F2_Sec { get; set; }
        public Nullable<int> F3_Sec { get; set; }
        public Nullable<int> F4_Sec { get; set; }
        public Nullable<int> F5_Sec { get; set; }
        public Nullable<int> F6_Sec { get; set; }
        public Nullable<int> F7_Sec { get; set; }
        public Nullable<int> F8_Sec { get; set; }
        public Nullable<int> F9_Sec { get; set; }
        public Nullable<int> F10_Sec { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual JunctionList JunctionList { get; set; }
    }
}
