//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupEnableDetail
    {
        public int Id { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public Nullable<bool> G1 { get; set; }
        public Nullable<bool> G2 { get; set; }
        public Nullable<bool> G3 { get; set; }
        public Nullable<bool> G4 { get; set; }
        public Nullable<bool> G5 { get; set; }
        public Nullable<bool> G6 { get; set; }
        public Nullable<bool> G7 { get; set; }
        public Nullable<bool> G8 { get; set; }
        public Nullable<bool> G9 { get; set; }
        public Nullable<bool> G10 { get; set; }
        public Nullable<bool> G11 { get; set; }
        public Nullable<bool> G12 { get; set; }
        public Nullable<bool> G13 { get; set; }
        public Nullable<bool> G14 { get; set; }
        public Nullable<bool> G15 { get; set; }
        public Nullable<bool> G16 { get; set; }
        public Nullable<bool> G17 { get; set; }
        public Nullable<bool> G18 { get; set; }
        public Nullable<bool> G19 { get; set; }
        public Nullable<bool> G20 { get; set; }
        public Nullable<bool> G21 { get; set; }
        public Nullable<bool> G22 { get; set; }
        public Nullable<bool> G23 { get; set; }
        public Nullable<bool> G24 { get; set; }
    
        public virtual JunctionList JunctionList { get; set; }
    }
}
