//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class JunctionVaTimeSetting
    {
        public int Id { get; set; }
        public Nullable<int> CompanyProfileId { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public Nullable<int> F1Gap { get; set; }
        public Nullable<int> F1Min { get; set; }
        public Nullable<int> F1Max { get; set; }
        public Nullable<int> F1Flh { get; set; }
        public Nullable<int> F1Amb { get; set; }
        public Nullable<int> F1Red { get; set; }
        public Nullable<int> F2Gap { get; set; }
        public Nullable<int> F2Min { get; set; }
        public Nullable<int> F2Max { get; set; }
        public Nullable<int> F2Flh { get; set; }
        public Nullable<int> F2Amb { get; set; }
        public Nullable<int> F2Red { get; set; }
        public Nullable<int> F3Gap { get; set; }
        public Nullable<int> F3Min { get; set; }
        public Nullable<int> F3Max { get; set; }
        public Nullable<int> F3Flh { get; set; }
        public Nullable<int> F3Amb { get; set; }
        public Nullable<int> F3Red { get; set; }
        public Nullable<int> F4Gap { get; set; }
        public Nullable<int> F4Min { get; set; }
        public Nullable<int> F4Max { get; set; }
        public Nullable<int> F4Flh { get; set; }
        public Nullable<int> F4Amb { get; set; }
        public Nullable<int> F4Red { get; set; }
        public Nullable<int> F5Gap { get; set; }
        public Nullable<int> F5Min { get; set; }
        public Nullable<int> F5Max { get; set; }
        public Nullable<int> F5Flh { get; set; }
        public Nullable<int> F5Amb { get; set; }
        public Nullable<int> F5Red { get; set; }
        public Nullable<int> F6Gap { get; set; }
        public Nullable<int> F6Min { get; set; }
        public Nullable<int> F6Max { get; set; }
        public Nullable<int> F6Flh { get; set; }
        public Nullable<int> F6Amb { get; set; }
        public Nullable<int> F6Red { get; set; }
        public Nullable<int> F7Gap { get; set; }
        public Nullable<int> F7Min { get; set; }
        public Nullable<int> F7Max { get; set; }
        public Nullable<int> F7Flh { get; set; }
        public Nullable<int> F7Amb { get; set; }
        public Nullable<int> F7Red { get; set; }
        public Nullable<int> F8Gap { get; set; }
        public Nullable<int> F8Min { get; set; }
        public Nullable<int> F8Max { get; set; }
        public Nullable<int> F8Flh { get; set; }
        public Nullable<int> F8Amb { get; set; }
        public Nullable<int> F8Red { get; set; }
        public Nullable<int> F9Gap { get; set; }
        public Nullable<int> F9Min { get; set; }
        public Nullable<int> F9Max { get; set; }
        public Nullable<int> F9Flh { get; set; }
        public Nullable<int> F9Amb { get; set; }
        public Nullable<int> F9Red { get; set; }
        public Nullable<int> F10Gap { get; set; }
        public Nullable<int> F10Min { get; set; }
        public Nullable<int> F10Max { get; set; }
        public Nullable<int> F10Flh { get; set; }
        public Nullable<int> F10Amb { get; set; }
        public Nullable<int> F10Red { get; set; }
    }
}
