//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class JunctionAlarm
    {
        public int Id { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string FaultyType { get; set; }
        public string Status { get; set; }
        public string Details { get; set; }
    
        public virtual JunctionList JunctionList { get; set; }
    }
}
