//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class JunctionMultiplanTimeSetting
    {
        public int Id { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public Nullable<int> F1_0 { get; set; }
        public Nullable<int> F1_1 { get; set; }
        public Nullable<int> F1_2 { get; set; }
        public Nullable<int> F1_3 { get; set; }
        public Nullable<int> F1_4 { get; set; }
        public Nullable<int> F1_5 { get; set; }
        public Nullable<int> F1_6 { get; set; }
        public Nullable<int> F1_7 { get; set; }
        public Nullable<int> F1_8 { get; set; }
        public Nullable<int> F1_9 { get; set; }
        public Nullable<int> F2_0 { get; set; }
        public Nullable<int> F2_1 { get; set; }
        public Nullable<int> F2_2 { get; set; }
        public Nullable<int> F2_3 { get; set; }
        public Nullable<int> F2_4 { get; set; }
        public Nullable<int> F2_5 { get; set; }
        public Nullable<int> F2_6 { get; set; }
        public Nullable<int> F2_7 { get; set; }
        public Nullable<int> F2_8 { get; set; }
        public Nullable<int> F2_9 { get; set; }
        public Nullable<int> F3_0 { get; set; }
        public Nullable<int> F3_1 { get; set; }
        public Nullable<int> F3_2 { get; set; }
        public Nullable<int> F3_3 { get; set; }
        public Nullable<int> F3_4 { get; set; }
        public Nullable<int> F3_5 { get; set; }
        public Nullable<int> F3_6 { get; set; }
        public Nullable<int> F3_7 { get; set; }
        public Nullable<int> F3_8 { get; set; }
        public Nullable<int> F3_9 { get; set; }
        public Nullable<int> F4_0 { get; set; }
        public Nullable<int> F4_1 { get; set; }
        public Nullable<int> F4_2 { get; set; }
        public Nullable<int> F4_3 { get; set; }
        public Nullable<int> F4_4 { get; set; }
        public Nullable<int> F4_5 { get; set; }
        public Nullable<int> F4_6 { get; set; }
        public Nullable<int> F4_7 { get; set; }
        public Nullable<int> F4_8 { get; set; }
        public Nullable<int> F4_9 { get; set; }
        public Nullable<int> F5_0 { get; set; }
        public Nullable<int> F5_1 { get; set; }
        public Nullable<int> F5_2 { get; set; }
        public Nullable<int> F5_3 { get; set; }
        public Nullable<int> F5_4 { get; set; }
        public Nullable<int> F5_5 { get; set; }
        public Nullable<int> F5_6 { get; set; }
        public Nullable<int> F5_7 { get; set; }
        public Nullable<int> F5_8 { get; set; }
        public Nullable<int> F5_9 { get; set; }
        public Nullable<int> F6_0 { get; set; }
        public Nullable<int> F6_1 { get; set; }
        public Nullable<int> F6_2 { get; set; }
        public Nullable<int> F6_3 { get; set; }
        public Nullable<int> F6_4 { get; set; }
        public Nullable<int> F6_5 { get; set; }
        public Nullable<int> F6_6 { get; set; }
        public Nullable<int> F6_7 { get; set; }
        public Nullable<int> F6_8 { get; set; }
        public Nullable<int> F6_9 { get; set; }
        public Nullable<int> F7_0 { get; set; }
        public Nullable<int> F7_1 { get; set; }
        public Nullable<int> F7_2 { get; set; }
        public Nullable<int> F7_3 { get; set; }
        public Nullable<int> F7_4 { get; set; }
        public Nullable<int> F7_5 { get; set; }
        public Nullable<int> F7_6 { get; set; }
        public Nullable<int> F7_7 { get; set; }
        public Nullable<int> F7_8 { get; set; }
        public Nullable<int> F7_9 { get; set; }
        public Nullable<int> F8_0 { get; set; }
        public Nullable<int> F8_1 { get; set; }
        public Nullable<int> F8_2 { get; set; }
        public Nullable<int> F8_3 { get; set; }
        public Nullable<int> F8_4 { get; set; }
        public Nullable<int> F8_5 { get; set; }
        public Nullable<int> F8_6 { get; set; }
        public Nullable<int> F8_7 { get; set; }
        public Nullable<int> F8_8 { get; set; }
        public Nullable<int> F8_9 { get; set; }
        public Nullable<int> F9_0 { get; set; }
        public Nullable<int> F9_1 { get; set; }
        public Nullable<int> F9_2 { get; set; }
        public Nullable<int> F9_3 { get; set; }
        public Nullable<int> F9_4 { get; set; }
        public Nullable<int> F9_5 { get; set; }
        public Nullable<int> F9_6 { get; set; }
        public Nullable<int> F9_7 { get; set; }
        public Nullable<int> F9_8 { get; set; }
        public Nullable<int> F9_9 { get; set; }
        public Nullable<int> F10_0 { get; set; }
        public Nullable<int> F10_1 { get; set; }
        public Nullable<int> F10_2 { get; set; }
        public Nullable<int> F10_3 { get; set; }
        public Nullable<int> F10_4 { get; set; }
        public Nullable<int> F10_5 { get; set; }
        public Nullable<int> F10_6 { get; set; }
        public Nullable<int> F10_7 { get; set; }
        public Nullable<int> F10_8 { get; set; }
        public Nullable<int> F10_9 { get; set; }
    
        public virtual JunctionList JunctionList { get; set; }
    }
}
