//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class JunctionPhasingFlow
    {
        public int Id { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public string Phase1 { get; set; }
        public string Phase2 { get; set; }
        public string Phase3 { get; set; }
        public string Phase4 { get; set; }
        public string Phase5 { get; set; }
        public string Phase6 { get; set; }
        public string Phase7 { get; set; }
        public string Phase8 { get; set; }
        public string Phase9 { get; set; }
        public string Phase10 { get; set; }
    }
}
