//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoopEnableDetail
    {
        public int Id { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public Nullable<bool> L1 { get; set; }
        public Nullable<bool> L2 { get; set; }
        public Nullable<bool> L3 { get; set; }
        public Nullable<bool> L4 { get; set; }
        public Nullable<bool> L5 { get; set; }
        public Nullable<bool> L6 { get; set; }
        public Nullable<bool> L7 { get; set; }
        public Nullable<bool> L8 { get; set; }
        public Nullable<bool> L9 { get; set; }
        public Nullable<bool> L10 { get; set; }
        public Nullable<bool> L11 { get; set; }
        public Nullable<bool> L12 { get; set; }
        public Nullable<bool> L13 { get; set; }
        public Nullable<bool> L14 { get; set; }
        public Nullable<bool> L15 { get; set; }
        public Nullable<bool> L16 { get; set; }
        public Nullable<bool> L17 { get; set; }
        public Nullable<bool> L18 { get; set; }
        public Nullable<bool> L19 { get; set; }
        public Nullable<bool> L20 { get; set; }
        public Nullable<bool> L21 { get; set; }
        public Nullable<bool> L22 { get; set; }
        public Nullable<bool> L23 { get; set; }
        public Nullable<bool> L24 { get; set; }
    
        public virtual JunctionList JunctionList { get; set; }
    }
}
