//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMonitoring
    {
        public int ID { get; set; }
        public string MonitoringString { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public string area_id { get; set; }
        public Nullable<int> CompanyProfileId { get; set; }
    }
}
