//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSale
    {
        public int SID { get; set; }
        public string area_id { get; set; }
        public string SQty { get; set; }
        public string MonitoringString { get; set; }
    }
}
