//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telegram
    {
        public int Id { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public string ClientEmailID { get; set; }
        public string JunctionId { get; set; }
        public Nullable<int> CompanyProfileId { get; set; }
        public string ComapnyName { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string BotName { get; set; }
        public string BotToken { get; set; }
        public string GroupId { get; set; }
    
        public virtual JunctionList JunctionList { get; set; }
    }
}
