//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaIntelligentSetting
    {
        public int Id { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public Nullable<int> CompanyProfileId { get; set; }
        public string F1VA_Maximun { get; set; }
        public string F1_MaxThreshhold { get; set; }
        public string F1_MinThreshhold { get; set; }
        public string F1_IncPriorty { get; set; }
        public string F1_DecPriorty { get; set; }
        public string F2VA_Maximun { get; set; }
        public string F2_MaxThreshhold { get; set; }
        public string F2_MinThreshhold { get; set; }
        public string F2_IncPriorty { get; set; }
        public string F2_DecPriorty { get; set; }
        public string F3VA_Maximun { get; set; }
        public string F3_MaxThreshhold { get; set; }
        public string F3_MinThreshhold { get; set; }
        public string F3_IncPriorty { get; set; }
        public string F3_DecPriorty { get; set; }
        public string F4VA_Maximun { get; set; }
        public string F4_MaxThreshhold { get; set; }
        public string F4_MinThreshhold { get; set; }
        public string F4_IncPriorty { get; set; }
        public string F4_DecPriorty { get; set; }
        public string F5VA_Maximun { get; set; }
        public string F5_MaxThreshhold { get; set; }
        public string F5_MinThreshhold { get; set; }
        public string F5_IncPriorty { get; set; }
        public string F5_DecPriorty { get; set; }
        public string F6VA_Maximun { get; set; }
        public string F6_MaxThreshhold { get; set; }
        public string F6_MinThreshhold { get; set; }
        public string F6_IncPriorty { get; set; }
        public string F6_DecPriorty { get; set; }
    }
}
