//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBBasedMITSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleCountArchive
    {
        public int Id { get; set; }
        public Nullable<int> JunctionListId { get; set; }
        public Nullable<int> F1_Vehicle { get; set; }
        public Nullable<int> F2_Vehicle { get; set; }
        public Nullable<int> F3_Vehicle { get; set; }
        public Nullable<int> F4_Vehicle { get; set; }
        public Nullable<int> F5_Vehicle { get; set; }
        public Nullable<int> F6_Vehicle { get; set; }
        public Nullable<int> F7_Vehicle { get; set; }
        public Nullable<int> F8_Vehicle { get; set; }
        public Nullable<int> F9_Vehicle { get; set; }
        public Nullable<int> F10_Vehicle { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
